apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
  creationTimestamp: 2019-01-28T03:09:58Z
  generation: 1
  labels:
    run: gke-cron-job-solution-1
  name: gke-cron-job-solution-1
  namespace: default
  resourceVersion: '1617'
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/gke-cron-job-solution-1
  uid: 31b4f68f-22aa-11e9-8b72-42010a8a01ab
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: gke-cron-job-solution-1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: gke-cron-job-solution-1
    spec:
      containers:
        - image: docker.io/novaline/gke-cron-job-solution-1:1.2
          imagePullPolicy: IfNotPresent
          name: gke-cron-job-solution-1
          volumeMounts:
            - name: google-application-credentials-volume
              mountPath: /etc/gcp
              readOnly: true
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: NODE_ENV
            - name: EMAIL_TO
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: EMAIL_TO
            - name: DAILY_REPORT_SCHEDULE
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: DAILY_REPORT_SCHEDULE
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/gcp/application-credentials.json
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: google-application-credentials-volume
          secret:
            secretName: google-application-credentials
            items:
              - key: application-credentials.json # default name created by the create secret from-file command
                path: application-credentials.json
status:
  conditions:
    - lastTransitionTime: 2019-01-28T03:09:58Z
      lastUpdateTime: 2019-01-28T03:09:58Z
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
    - lastTransitionTime: 2019-01-28T03:09:58Z
      lastUpdateTime: 2019-01-28T03:10:12Z
      message: ReplicaSet "gke-cron-job-solution-1-6d496cd695" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
