apiVersion: v1
items:
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      annotations:
        deployment.kubernetes.io/revision: '3'
      creationTimestamp: 2019-02-11T09:26:35Z
      generation: 3
      labels:
        run: nodejs-gcp
      name: nodejs-gcp
      namespace: default
      resourceVersion: '6920'
      selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/nodejs-gcp
      uid: 20935c41-2ddf-11e9-abf8-42010a8a004d
    spec:
      progressDeadlineSeconds: 600
      replicas: 1
      revisionHistoryLimit: 10
      selector:
        matchLabels:
          run: nodejs-gcp
      strategy:
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 1
        type: RollingUpdate
      template:
        metadata:
          creationTimestamp: null
          labels:
            run: nodejs-gcp
        spec:
          volumes:
            - name: google-application-credentials-volume
              secret:
                secretName: google-application-credentials
                items:
                  - key: application-credentials.json
                    path: application-credentials.json
          containers:
            - image: asia.gcr.io/shadowsocks-218808/app:1.6
              imagePullPolicy: Always
              volumeMounts:
                - name: google-application-credentials-volume
                  mountPath: /etc/gcp
                  readOnly: true
              name: nodejs-gcp
              env:
                - name: KEY_FILE_NAME
                  value: /etc/gcp/application-credentials.json
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
    status:
      conditions:
        - lastTransitionTime: 2019-02-11T09:26:35Z
          lastUpdateTime: 2019-02-11T09:26:35Z
          message: Deployment has minimum availability.
          reason: MinimumReplicasAvailable
          status: 'True'
          type: Available
        - lastTransitionTime: 2019-02-11T09:26:35Z
          lastUpdateTime: 2019-02-11T09:56:40Z
          message: ReplicaSet "nodejs-gcp-8cb6f79b4" has successfully progressed.
          reason: NewReplicaSetAvailable
          status: 'True'
          type: Progressing
      observedGeneration: 3
      replicas: 1
      unavailableReplicas: 1
      updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ''
  selfLink: ''
