service: gae-standard-cloud-sql
runtime: nodejs8
env_variables:
  SQL_USER: dul
  SQL_PASSWORD: 365715693
  SQL_DATABASE: nodejs-gcp
  INSTANCE_CONNECTION_NAME: just-aloe-212502:us-central1:nodejs-gcp
  PORT: 8080
  NODE_ENV: production
