apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
  creationTimestamp: 2019-01-28T08:45:41Z
  generation: 1
  labels:
    run: nodejs-hello-world
  name: nodejs-hello-world
  namespace: default
  resourceVersion: '12916'
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/nodejs-hello-world
  uid: 180c10c1-22d9-11e9-bcfb-42010a8a012d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: nodejs-hello-world
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: nodejs-hello-world
    spec:
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
      containers:
        - image: docker.io/novaline/nodejs-hello-world:2.0.1
          imagePullPolicy: IfNotPresent
          name: nodejs-hello-world
          ports:
            - containerPort: 3200
              protocol: TCP
          env:
            - name: PORT
              value: '3200'
            - name: SQL_DATABASE
              value: 'avstar'
            - name: SQL_USER
              valueFrom:
                secretKeyRef:
                  key: SQL_USER
                  name: cloud-db-credentials
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: SQL_PASSWORD
                  name: cloud-db-credentials
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          command:
            [
              '/cloud_sql_proxy',
              '-instances=shadowsocks-218808:us-central1:nodejs-gcp-2=tcp:5432',
              '-credential_file=/secrets/cloudsql/credentials.json',
            ]
          securityContext:
            runAsUser: 2 # non-root user
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: 2019-01-28T08:45:41Z
      lastUpdateTime: 2019-01-28T08:45:41Z
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
    - lastTransitionTime: 2019-01-28T08:45:41Z
      lastUpdateTime: 2019-01-28T08:45:43Z
      message: ReplicaSet "nodejs-hello-world-6d7f68bd75" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
