apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
  creationTimestamp: 2019-01-28T10:47:08Z
  generation: 1
  labels:
    run: nodejs-gcp
  name: nodejs-gcp
  namespace: default
  resourceVersion: '1830'
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/nodejs-gcp
  uid: 0f40f177-22ea-11e9-be0a-42010a8a019d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: nodejs-gcp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: nodejs-gcp
    spec:
      containers:
        - image: docker.io/novaline/gke-cron-job-solution-3:1.5
          imagePullPolicy: IfNotPresent
          name: nodejs-gcp
          volumeMounts:
            - name: google-application-credentials-volume
              mountPath: /etc/gcp
              readOnly: true
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: NODE_ENV
            - name: EMAIL_TO
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: EMAIL_TO
            - name: DAILY_REPORT_SCHEDULE
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: DAILY_REPORT_SCHEDULE
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/gcp/application-credentials.json
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: google-application-credentials-volume
          secret:
            secretName: google-application-credentials
            items:
              - key: application-credentials.json # default name created by the create secret from-file command
                path: application-credentials.json
status:
  conditions:
    - lastTransitionTime: 2019-01-28T10:47:08Z
      lastUpdateTime: 2019-01-28T10:47:08Z
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
    - lastTransitionTime: 2019-01-28T10:47:08Z
      lastUpdateTime: 2019-01-28T10:47:22Z
      message: ReplicaSet "nodejs-gcp-664f448688" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
