service: create-react-app
runtime: nodejs8
# env_variables:
# NODE_ENV: development
# API_ENDPOINT: github.com
handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html
  - url: /
    static_dir: build
