service: gae-standard-cloud-sql
runtime: nodejs8
instance_class: F1
env_variables:
  SQL_USER: postgres
  SQL_PASSWORD: 365715693
  SQL_DATABASE: nodejs-pg-knex-samples
  INSTANCE_CONNECTION_NAME: shadowsocks-218808:us-central1:nodejs-gcp
  PORT: 8080
  NODE_ENV: production
