service: create-react-app
runtime: nodejs8
env_variables:
  NODE_ENV: development
handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html
  - url: /
    static_dir: build
